### PR TITLE
Fix broken things

### PR DESCRIPTION
**Pull request by LiruMouse**
Fix and optimize only-playercommands being off.
Restore the checks for clothing items that were removed probably because the materials were changed.

### CODE REVIEW

**Comment by Peda1996** [comment]
I think you cleaned it up right ^^. When i was writing this it was late in the night and I was setting up my server (it is working on mc.buildbros.tk this way xD) yea i messed up a bit, and never fixed it correctly. 

Thank you for fixing my bad code style.

**Comment by Peda1996** [comment]
Have you tried out the functionality of the plugin?

**Comment by LiruMouse** [comment]
The protection? No, not yet.

**Comment by Peda1996** [comment]
Well i have tried it out, and added Placeholder Support for lores and titles. (commit aff80f086687af54f378fd384f0726d5f7b820e4)

My only problem was that
Restore functionality to is<Clothing> methods
was breaking the plugin, therefore i removed the functionality.. 

I am waiting for a fix for this ^^

Well don't know on my testing server it worked, but now on my main server it wont.. I dont get it..

**Comment by LiruMouse** [comment]
Hm... That's strange, what exactly did it break? On our server it's working
fine as is.

**Comment by Peda1996** [comment]
That's the problem:
No error log nothing, just the commands won't work anymore

Nice everything seems to work now, so I am also using this as my main bungeecord plugin, in combination with MicroJump.
image

**Pull request merged**
